version: 3
services:
    app-nodejs:
        container_name: app-nodejs
        build: .
        dockerfile: Dockerfile
        ports:
            3000:3000
        volumes:
            - /opt/jenkins_app/workspace/hello-nodejs:/app